version: "3"

services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - BLOG_DATABASE_HOST=postgres
      - BLOG_DATABASE_USERNAME=postgres
      - BLOG_DATABASE_PASSWORD=root
      - BLOG_HOST_PROTOCOL=https

volumes:
  postgresqldata:
